# Generated by Django 6.0.6 on 2026-06-19 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='date_delivrance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('delivree', 'Délivrée')], default='en_attente', max_length=20),
        ),
    ]
